### PR TITLE
Add docs + example

### PR DESCRIPTION
**Pull request by sinedied**
- Merged latest changes from `main` (was needed to make the docs up to date)
- Added tool documentation
- Added tool reference in Microsoft platform docs
- Added readme for the package
- Added example usage (simple + agent)
- Fixed CJS build (added workaround to make the code compatible with both ESM/CJS)

### CODE REVIEW

**Comment by sinedied** [comment]
@anthonychu could you merge the latest upstream `main` branch into your branch, so I can rebase this PR and make it more bearable to read? GH is suffering from all the changes 😅

**Comment by anthonychu** [comment]
Done! Let me know if I messed something up. #3

**Comment by sinedied** [comment]
I updated the PR, it's readable now :)

**Comment by sinedied** [comment]
I fixed the langchain/core dependency, build and tests are green now

**Review by anthonychu — APPROVED** [review]

**Pull request merged**
